version: '3'
services:
  db:
    build:
      context: .
      dockerfile: ./dockerfiles/postgres.dockerfile
    environment:
      - POSTGRES_DB=ai
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
    ports:
      - "5432:5432"